In [39]:
# Constant trong tensorflow
import tensorflow as tf
x = tf.constant(5,tf.float32)
y = tf.constant([5], tf.float32)
z = tf.constant([5,3,4], tf.float32)
t = tf.constant([[5,3,4,6],[2,3,4,7]], tf.float32)
u = tf.constant([[[5,3,4,6],[2,3,4,0]]], tf.float32)
v = tf.constant([[[5,3,4,6],[2,3,4,0]],
 [[5,3,4,6],[2,3,4,0]],
[[5,3,4,6],[2,3,4,0]]
 ], tf.float32)
print(y)


Tensor("Const_7:0", shape=(1,), dtype=float32)


In [40]:
# Variable trong tensorflow
import tensorflow.compat.v1 as tf

tf.compat.v1.disable_eager_execution()
x1 = tf.Variable(5.3, tf.float32)
x2 = tf.Variable(4.3, tf.float32)
x = tf.multiply(x1,x2)
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  t = sess.run(x)
  print(t)


22.79


In [41]:
import tensorflow.compat.v1 as tf

tf.compat.v1.disable_eager_execution()
x1 = tf.Variable([[5.3,4.5,6.0],
 [4.3,4.3,7.0]
 ], tf.float32)
x2 = tf.Variable([[4.3,4.3,7.0],
 [5.3,4.5,6.0]
 ], tf.float32)
x = tf.multiply(x1,x2)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    t = sess.run(x)
    print(t)

[[22.79 19.35 42.  ]
 [22.79 19.35 42.  ]]


In [42]:
# Placeholder
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x = tf.placeholder(tf.float32,None)
y = tf.add(x,x)
with tf.Session() as sess:
 x_data= 5
 result = sess.run(y,feed_dict={x:x_data})
 print(result)


10.0


In [43]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x = tf.placeholder(tf.float32,[None,3])
y = tf.add(x,x)
with tf.Session() as sess:
 x_data= [[1.5, 2.0, 3.3]]
 result = sess.run(y,feed_dict={x:x_data})
 print(result)


[[3.  4.  6.6]]


In [44]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x = tf.placeholder(tf.float32,[None,None,3])
y = tf.add(x,x)
with tf.Session() as sess:
 x_data= [[[1,2,3]]]
 result = sess.run(y,feed_dict={x:x_data})
 print(result)

[[[2. 4. 6.]]]


In [45]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x = tf.placeholder(tf.float32,[None,4,3])
y = tf.add(x,x)
with tf.Session() as sess:
 x_data= [[[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ]]
 result = sess.run(y,feed_dict={x:x_data})
 print(result)


[[[ 2.  4.  6.]
  [ 4.  6.  8.]
  [ 4.  6. 10.]
  [ 0.  2.  4.]]]


In [46]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x = tf.placeholder(tf.float32,[2,4,3])
y = tf.add(x,x)
with tf.Session() as sess:
 x_data= [[[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ],
 [[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ]]
 result = sess.run(y,feed_dict={x:x_data})
 print(result)


[[[ 2.  4.  6.]
  [ 4.  6.  8.]
  [ 4.  6. 10.]
  [ 0.  2.  4.]]

 [[ 2.  4.  6.]
  [ 4.  6.  8.]
  [ 4.  6. 10.]
  [ 0.  2.  4.]]]


In [47]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x = tf.placeholder(tf.float32,[2,4,3])
y = tf.placeholder(tf.float32,[2,4,3])
z = tf.add(x,y)
u = tf.multiply(x,y)
with tf.Session() as sess:
 x_data= [[[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ],
 [[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ]]
 y_data= [[[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ],
 [[1,2,3],
 [2,3,4],
 [2,3,5],
 [0,1,2]
 ]]
 result1 = sess.run(z,feed_dict={x:x_data, y:y_data})
 result2 = sess.run(u,feed_dict={x:x_data, y:y_data})
 print("result1 =", result1)
 print("result2 =", result2)


result1 = [[[ 2.  4.  6.]
  [ 4.  6.  8.]
  [ 4.  6. 10.]
  [ 0.  2.  4.]]

 [[ 2.  4.  6.]
  [ 4.  6.  8.]
  [ 4.  6. 10.]
  [ 0.  2.  4.]]]
result2 = [[[ 1.  4.  9.]
  [ 4.  9. 16.]
  [ 4.  9. 25.]
  [ 0.  1.  4.]]

 [[ 1.  4.  9.]
  [ 4.  9. 16.]
  [ 4.  9. 25.]
  [ 0.  1.  4.]]]


In [48]:
# Operation
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x1 = tf.constant(5.3, tf.float32)
x2 = tf.constant(1.5, tf.float32)
w1 = tf.Variable(0.7, tf.float32)
w2 = tf.Variable(0.5, tf.float32)
u = tf.multiply(x1,w1)
v = tf.multiply(x2,w2)
z = tf.add(u,v)
result = tf.sigmoid(z)
init = tf.global_variables_initializer()
with tf.Session() as sess:
 sess.run(init)
 print(sess.run(result))

0.9885698


In [49]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
x1 = tf.placeholder(tf.float32,[None,3])
x2 = tf.placeholder(tf.float32,[None,3])
w1 = tf.Variable([0.5,0.4,0.7],tf.float32)
w2 = tf.Variable([0.8,0.5,0.6], tf.float32)

u1 = tf.multiply(w1,x1)
u2 = tf.multiply(w2,x2)
v = tf.add(u1,u2)
z = tf.sigmoid(v)
init = tf.global_variables_initializer()
with tf.Session() as sess:
 x1_data= [[1,2,3]]
 x2_data= [[1,2,3]]
 sess.run(init)
 result = sess.run(z,feed_dict={x1:x1_data, x2:x2_data})
 print(result)

[[0.785835   0.85814893 0.9801597 ]]


In [52]:
#Import required packages
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

np.random.seed(2018)
train_data, test_data = np.random.random((1000, 3)), np.random.random((500, 3))

labels = np.random.randint(2, size=(1000, 1))

model = Sequential()
model.add(Dense(5, input_dim=3, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(train_data, labels, epochs=10, batch_size=32)

predictions = model.predict(test_data)

# print(predictions )


Train on 1000 samples
Epoch 1/10
1000/1000 [==============================] - 0s 85us/sample - loss: 0.7171 - accuracy: 0.5070
Epoch 2/10
1000/1000 [==============================] - 0s 19us/sample - loss: 0.7051 - accuracy: 0.5020
Epoch 3/10
1000/1000 [==============================] - 0s 18us/sample - loss: 0.6997 - accuracy: 0.4930
Epoch 4/10
1000/1000 [==============================] - 0s 23us/sample - loss: 0.6974 - accuracy: 0.4950
Epoch 5/10
1000/1000 [==============================] - 0s 20us/sample - loss: 0.6962 - accuracy: 0.4960
Epoch 6/10
1000/1000 [==============================] - 0s 20us/sample - loss: 0.6959 - accuracy: 0.5060
Epoch 7/10
1000/1000 [==============================] - 0s 21us/sample - loss: 0.6952 - accuracy: 0.5120
Epoch 8/10
1000/1000 [==============================] - 0s 21us/sample - loss: 0.6949 - accuracy: 0.5080
Epoch 9/10
1000/1000 [==============================] - 0s 19us/sample - loss: 0.6945 - accuracy: 0.5130
Epoch 10/10
1000/1000 [==========

In [54]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation

np.random.seed(2018)
x_train = np.random.random((6000,10))
y_train = np.random.randint(2, size=(6000, 1))

x_val = np.random.random((2000,10))
y_val = np.random.randint(2, size=(2000, 1))

x_test = np.random.random((2000,10))
y_test = np.random.randint(2, size=(2000, 1))

model = Sequential()
model.add(Dense(64, input_dim=10,activation = "relu")) #Layer 1
model.add(Dense(32,activation = "relu")) #Layer 2
model.add(Dense(16,activation = "relu")) #Layer 3
model.add(Dense(8,activation = "relu")) #Layer 4
model.add(Dense(4,activation = "relu")) #Layer 5
model.add(Dense(1,activation = "sigmoid")) #OutputLayer

model.compile(optimizer='Adam',loss='binary_crossentropy', metrics =['accuracy'])
#Train the model
model.fit(x_train, y_train, batch_size=64, epochs=3, validation_data=(x_val,y_val))

print(model.evaluate(x_test,y_test))
print(model.metrics_names)

pred = model.predict(x_test)
pred[:10]


Train on 6000 samples, validate on 2000 samples
Epoch 1/3
6000/6000 [==============================] - 0s 41us/sample - loss: 0.6934 - accuracy: 0.4943 - val_loss: 0.6931 - val_accuracy: 0.5010
Epoch 2/3
6000/6000 [==============================] - 0s 12us/sample - loss: 0.6932 - accuracy: 0.4962 - val_loss: 0.6927 - val_accuracy: 0.5185
Epoch 3/3


c:\Users\LeeJaeLee\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training_v1.py:2333: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates = self.state_updates


6000/6000 [==============================] - 0s 13us/sample - loss: 0.6931 - accuracy: 0.5022 - val_loss: 0.6928 - val_accuracy: 0.5150
[0.69316916847229, 0.5075]
['loss', 'accuracy']


array([[0.5034246 ],
       [0.50593805],
       [0.5063935 ],
       [0.4945562 ],
       [0.5053979 ],
       [0.49981505],
       [0.501139  ],
       [0.5052259 ],
       [0.5003386 ],
       [0.49709842]], dtype=float32)